package com.core.coreboot.exception;

/**
 * 异常枚举
 */
public enum ExceptionEnum {
    NEED_USER_NAME(10001, "用户名不能为空"),
    NEED_PASSWORD(10002, "密码不能为空"),
    PASSWORD_TOO_SHORT(10003, "密码长度不能小于6位"),
    NAME_EXISTED(10004, "名称重复"),
    INSERT_FAILED(10005, "新增失败，请重试"),
    WRONG_USERNAME_OR_PASSWORD(10006, "用户名或密码错误"),
    NEED_LOGGED(10007, "用户未登录"),
    UPDATE_FAILED(10008, "更新失败"),
    NEED_ADMIN(10009, "无管理员权限"),
    NEED_PARA(10010, "参数不能为空"),
    WRONG_PARA(10011, "参数错误"),
    DELETE_FAILED(10012, "删除失败"),
    MKDIR_FAILED(10013, "文件夹创建失败"),
    FILE_UPLOAD_FAILED(10014, "文件上传失败"),
    IMAGE_UPLOAD_FAILED(10015, "图片上传失败"),
    ONLY_IMAGE_ALLOWED(10016, "只允许上传图片格式"),
    PRODUCT_STATUS_UNUSUAL(10017, "商品状态异常"),
    PRODUCT_STOCK_NOT_ENOUGH(10018, "商品库存不足"),
    CART_NOT_SELECTED(10019, "未勾选商品"),
    NO_ENUM(10020, "未找到对应枚举"),
    NO_ORDER(10021, "订单不存在"),
    NOT_YOUR_ORDER(10022, "订单不属于你"),
    WRONG_ORDER_STATUS(10023, "订单状态异常"),
    TOKEN_EXPIRED(10024, "token已过期"),
    TOKEN_WRONG(10025, "token解析异常"),
    NOT_EXIST(10026, "指定查询不存在"),
    PLATFORM_CUSTOMER_NOT_FOUND(30001, "客户不存在"),
    PLATFORM_CUSTOMER_DISABLED(30002, "客户账户不可用"),
    PLATFORM_STORE_NOT_FOUND(30003, "门店不存在"),
    PLATFORM_STORE_UNAVAILABLE(30004, "门店当前不可操作"),
    PLATFORM_OPERATOR_NOT_FOUND(30005, "后台操作员不存在"),
    PLATFORM_OPERATOR_DISABLED(30006, "后台操作员账户不可用"),
    PLATFORM_STORE_ACCESS_DENIED(30007, "操作员没有该门店的数据权限"),
    PLATFORM_RECHARGE_AMOUNT_INVALID(30008, "充值金额必须是大于0的整元金额"),
    PLATFORM_PAYMENT_REFERENCE_REQUIRED(30009, "平台收款交易参考号不能为空"),
    PLATFORM_PAYMENT_REFERENCE_USED(30010, "该平台收款交易已经入账"),
    PLATFORM_IDEMPOTENCY_CONFLICT(30011, "幂等键已被不同的请求使用"),
    PLATFORM_POINT_ACCOUNT_ERROR(30012, "积分账户更新失败"),
    PLATFORM_RECHARGE_WRITE_FAILED(30013, "充值入账失败"),
    PLATFORM_INVALID_REQUEST(30014, "请求参数不符合积分平台规则"),
    PLATFORM_ADMIN_LOGIN_FAILED(30015, "后台用户名或密码错误"),
    PLATFORM_ADMIN_SECURITY_NOT_CONFIGURED(30016, "后台认证密钥未正确配置"),
    PLATFORM_ADMIN_TOKEN_INVALID(30017, "后台登录凭证无效或已过期"),
    PLATFORM_ADMIN_AUTHORITY_INVALID(30018, "后台账号权限配置异常"),
    PLATFORM_ADMIN_BOOTSTRAP_INVALID(30019, "超级管理员初始化配置无效"),
    PLATFORM_ADMIN_ACCESS_DENIED(30020, "后台账号无权执行该操作"),
    PLATFORM_DATA_CONFLICT(30021, "数据已被其他请求处理，请刷新后重试"),
    PLATFORM_CONSUMPTION_POINTS_INVALID(30022, "消费积分必须是大于0的整数"),
    PLATFORM_POINT_BALANCE_INSUFFICIENT(30023, "客户积分余额不足"),
    PLATFORM_CUSTOMER_HAS_PENDING_CONSUMPTION(30024, "客户已有待确认的消费订单"),
    PLATFORM_CONSUMPTION_PREPARE_FAILED(30025, "消费订单创建失败"),
    PLATFORM_CONSUMPTION_CONFIGURATION_INVALID(30026, "消费订单有效期配置无效"),
    PLATFORM_CONSUME_PIN_FORMAT_INVALID(30027, "消费密码必须为6位数字，且不能使用过于简单的密码"),
    PLATFORM_CONSUME_PIN_ALREADY_SET(30028, "消费密码已经设置，请使用修改密码功能"),
    PLATFORM_CONSUME_PIN_NOT_SET(30029, "尚未设置消费密码"),
    PLATFORM_CONSUME_PIN_INCORRECT(30030, "消费密码错误"),
    PLATFORM_CONSUME_PIN_LOCKED(30031, "消费密码连续输错，已被临时锁定"),
    PLATFORM_CONSUME_PIN_UNCHANGED(30032, "新消费密码不能与原密码相同"),
    PLATFORM_CUSTOMER_PIN_CONFIGURATION_INVALID(30033, "消费密码安全配置无效"),
    PLATFORM_CUSTOMER_TOKEN_INVALID(30034, "客户登录凭证无效或已过期"),
    PLATFORM_CUSTOMER_SECURITY_NOT_CONFIGURED(30035, "客户认证密钥未正确配置"),
    PLATFORM_CUSTOMER_LOGIN_TICKET_INVALID(30036, "登录票据无效、已过期或已经使用"),
    PLATFORM_CUSTOMER_ACCESS_DENIED(30037, "客户账号无权执行该操作"),
    PLATFORM_WECHAT_AUTH_NOT_CONFIGURED(30038, "微信登录尚未配置"),
    PLATFORM_WECHAT_AUTH_STATE_INVALID(30039, "微信登录状态无效或已过期，请重新登录"),
    PLATFORM_WECHAT_AUTH_FAILED(30040, "微信授权失败，请重新登录"),
    PLATFORM_WECHAT_API_UNAVAILABLE(30041, "微信服务暂不可用，请稍后重试"),
    PLATFORM_PHONE_VERIFICATION_NOT_CONFIGURED(30042, "短信验证码服务尚未配置"),
    PLATFORM_PHONE_VERIFICATION_TOO_FREQUENT(30043, "验证码发送过于频繁，请稍后再试"),
    PLATFORM_PHONE_VERIFICATION_LIMIT_REACHED(30044, "验证码发送次数已达上限，请稍后再试"),
    PLATFORM_PHONE_VERIFICATION_INVALID(30045, "验证码错误或已过期，请重新获取"),
    PLATFORM_PHONE_VERIFICATION_LOCKED(30046, "验证码连续输错，请重新获取"),
    PLATFORM_PHONE_ALREADY_BOUND(30047, "当前账户已经绑定手机号"),
    PLATFORM_PHONE_ALREADY_USED(30048, "该手机号暂时无法绑定，请联系客服处理"),
    PLATFORM_PHONE_BIND_FAILED(30049, "手机号绑定失败，请稍后重试"),
    PLATFORM_SMS_SEND_FAILED(30050, "短信发送失败，请稍后重试"),
    PLATFORM_CAPTCHA_REQUIRED(30051, "需要完成人机验证后再发送短信"),
    PLATFORM_PHONE_NOT_BOUND(30052, "请先绑定手机号"),
    PLATFORM_CONSUMPTION_ORDER_NOT_FOUND(30053, "待确认消费订单不存在"),
    PLATFORM_CONSUMPTION_ORDER_NOT_PENDING(30054, "消费订单当前状态不允许确认"),
    PLATFORM_CONSUMPTION_ORDER_EXPIRED(30055, "消费订单已过期，请让门店重新发起"),
    PLATFORM_CONSUMPTION_CONFIRM_FAILED(30056, "消费确认失败，请刷新后重试"),
    PLATFORM_RECHARGE_ORDER_NOT_FOUND(30057, "充值订单不存在"),
    PLATFORM_RECHARGE_NOT_REFUNDABLE(30058, "该充值订单当前不允许退款"),
    PLATFORM_RECHARGE_POINTS_ALREADY_USED(30059, "该笔充值积分已经发生过消费，不能退款"),
    PLATFORM_REFUND_REFERENCE_REQUIRED(30060, "实际退款交易参考号不能为空"),
    PLATFORM_REFUND_REFERENCE_USED(30061, "该退款交易已经登记"),
    PLATFORM_RECHARGE_REFUND_WRITE_FAILED(30062, "充值退款登记失败，请刷新后重试"),
    PLATFORM_SETTLEMENT_PERIOD_INVALID(30063, "结算月份格式不正确，请使用YYYY-MM"),
    PLATFORM_SETTLEMENT_PERIOD_NOT_CLOSED(30064, "只能为已经结束的自然月生成结算单"),
    PLATFORM_SETTLEMENT_NO_ELIGIBLE_ORDERS(30065, "该月份没有可结算的消费订单"),
    PLATFORM_SETTLEMENT_NOT_FOUND(30066, "门店结算单不存在"),
    PLATFORM_SETTLEMENT_STATE_INVALID(30067, "门店结算单当前状态不允许该操作"),
    PLATFORM_SETTLEMENT_ACCESS_DENIED(30068, "后台账号无权查看或操作该门店结算单"),
    PLATFORM_SETTLEMENT_PAYMENT_REFERENCE_REQUIRED(30069, "结算付款交易参考号不能为空"),
    PLATFORM_SETTLEMENT_PAYMENT_REFERENCE_USED(30070, "该结算付款交易已经登记"),
    PLATFORM_SETTLEMENT_WRITE_FAILED(30071, "门店结算处理失败，请刷新后重试"),
    PLATFORM_SETTLEMENT_DATA_INVALID(30072, "结算基础数据异常，请联系平台管理员处理"),
    PLATFORM_MERCHANT_NOT_FOUND(30073, "合作商户不存在"),
    PLATFORM_MERCHANT_UNAVAILABLE(30074, "合作商户当前不可用"),
    PLATFORM_STORE_CODE_USED(30075, "门店编码已被使用"),
    PLATFORM_STORE_STATUS_INVALID(30076, "门店状态变更不符合规则"),
    PLATFORM_STORE_MANAGEMENT_WRITE_FAILED(30077, "门店资料保存失败，请刷新后重试"),
    PLATFORM_MERCHANT_CODE_USED(30078, "合作商户编码已被使用"),
    PLATFORM_MERCHANT_CREDIT_CODE_USED(30079, "统一社会信用代码已被使用"),
    PLATFORM_MERCHANT_STATUS_INVALID(30080, "合作商户状态变更不符合规则"),
    PLATFORM_MERCHANT_MANAGEMENT_WRITE_FAILED(30081, "合作商户资料保存失败，请刷新后重试"),
    SYSTEM_ERROR(20000, "系统异常"),
    REDIS_CONNECTION_ERROR(20001, "Redis缓存服务暂不可用"),
    MYSQL_CONNECTION_ERROR(20002, "MySQL数据库服务暂不可用");

    Integer code;
    String msg;

    ExceptionEnum(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
}
